# roles/tailscale_manage/tasks/install.yaml
- name: Install Tailscale on Windows
  block:
    - name: Set Windows-specific variables
      set_fact:
        tailscale_msi_url: "https://pkgs.tailscale.com/stable/tailscale-setup-latest-{{ 'amd64' if is_64bit else 'x86' }}.msi"
        program_files_dir: "{{ ansible_env.ProgramFiles if is_64bit else ansible_env.ProgramFiles(x86) | default(ansible_env.ProgramFiles) }}"

    - name: Create Tailscale directory
      win_file:
        path: '{{ program_files_dir }}\\Tailscale'
        state: directory

    - name: Download Tailscale MSI
      win_get_url:
        url: "{{ tailscale_msi_url }}"
        dest: '{{ program_files_dir }}\\Tailscale\\tailscale-setup.msi'

    - name: Install Tailscale
      win_package:
        path: '{{ program_files_dir }}\\Tailscale\\tailscale-setup.msi'
        state: present
        arguments: /quiet TS_INSTALLDIR="{{ program_files_dir }}\\Tailscale"

    - name: Ensure Tailscale service is running
      win_service:
        name: Tailscale
        state: started
        start_mode: auto

    - name: Connect to Tailscale network
      win_command: '"{{ program_files_dir }}\\Tailscale\\tailscale.exe" up --authkey {{ tailscale_authkey }}'
      args:
        creates: '{{ ansible_env.ProgramData }}\\Tailscale\\tailscaled.state'
  when: ansible_os_family == "Windows"

- name: Install Tailscale on Linux
  block:
    - name: Download Tailscale installation script
      ansible.builtin.get_url:
        url: https://tailscale.com/install.sh
        dest: /tmp/tailscale_install.sh
        mode: '0700'
      become: yes

    - name: Run Tailscale installation script
      ansible.builtin.command: /tmp/tailscale_install.sh
      become: yes

    - name: Remove Tailscale installation script
      ansible.builtin.file:
        path: /tmp/tailscale_install.sh
        state: absent
      become: yes
      
    - name: Connect to Tailscale network
      ansible.builtin.command: tailscale up --authkey {{ tailscale_authkey }}
      args:
        creates: /var/lib/tailscale/tailscaled.state
      become: yes
  when: ansible_os_family != "Windows"