# roles/tailscale_manage/tasks/install.yml

- name: Install Tailscale on Windows
  block:
    - name: Download Tailscale MSI
      win_get_url:
        url: https://pkgs.tailscale.com/stable/tailscale-setup-latest-amd64.msi
        dest: '{{ windows_system_drive }}\\Program Files\\Tailscale\\tailscale-setup.msi'

    - name: Install Tailscale
      win_package:
        path: '{{ windows_system_drive }}\\Program Files\\Tailscale\\tailscale-setup.msi'
        state: present
        arguments: /quiet TS_INSTALLDIR="{{ windows_system_drive }}\\Program Files\\Tailscale"

    - name: Ensure Tailscale service is running
      win_service:
        name: Tailscale
        state: started
        start_mode: auto

    - name: Connect to Tailscale network
      win_command: '"{{ windows_system_drive }}\\Program Files\\Tailscale\\tailscale.exe" up --authkey {{ tailscale_authkey }}'
      args:
        creates: '{{ windows_system_drive }}\\ProgramData\\Tailscale\\tailscaled.state'
  when: ansible_os_family == "Windows"

- name: Install Tailscale on Linux
  block:
    - name: Download and run Tailscale installation script
      ansible.builtin.shell: curl -fsSL https://tailscale.com/install.sh | sh
      args:
        warn: false
      become: yes


    - name: Connect to Tailscale network
      ansible.builtin.command: tailscale up --authkey {{ tailscale_authkey }}
      args:
        creates: /var/lib/tailscale/tailscaled.state
      become: yes
  when: ansible_os_family != "Windows"
