# roles/tailscale_manage/tasks/install.yaml
- name: Install Tailscale on Windows
  when: ansible_os_family == "Windows"
  ansible.builtin.include_tasks: windows-install.yaml

- name: Install Tailscale on Linux
  when: ansible_os_family != "Windows"
  ansible.builtin.include_tasks: linux-install.yaml