- name: Get device ID on Linux
  when: ansible_os_family != 'Windows'
  ansible.builtin.shell: |
    tailscale status --json | python3 -c "import sys, json; print(json.load(sys.stdin)['Self']['ID'])"
  register: tailscale_status_linux
  ignore_errors: true

- name: Set device ID fact
  when: 
    - ansible_os_family != 'Windows'
    - tailscale_status_linux is success
  set_fact:
    tailscale_device_id: "{{ tailscale_status_linux.stdout | default(true) }}"

- name: Uninstall Tailscale on Linux
  when: ansible_os_family != "Windows"
  block:
    - name: Remove Tailscale package
      become: true
      ansible.builtin.package:
        name: "tailscale"
        state: absent
      register: tailscale_uninstall_result
      ignore_errors: true

    - name: Check if Tailscale is still installed
      become: true
      ansible.builtin.package:
        name: "tailscale"
        state: absent
      check_mode: true
      register: tailscale_check_result
      ignore_errors: true

    - name: Warn user if Tailscale is still installed
      ansible.builtin.debug:
        msg: "Tailscale is still installed on {{ ansible_distribution }}. Please uninstall it manually."
      when: tailscale_check_result.changed

    - name: Remove Tailscale data directory
      ansible.builtin.file:
        path: /var/lib/tailscale
        state: absent
      become: true
      become_user: root

    - name: Remove Tailscale configuration
      ansible.builtin.file:
        path: /etc/tailscale
        state: absent
      become: true
      become_user: root
- name: Remove device from tailnet
  uri:
    url: "https://api.tailscale.com/api/v2/device/{{ tailscale_device_id }}"
    method: DELETE
    headers:
      Authorization: "Bearer {{ tailscale_api_key }}"
  delegate_to: localhost
  register: result

- name: Debug the result
  debug:
    var: result