---
# roles/tailscale_manage/tasks/main.yaml

- name: Gather facts if needed
  ansible.builtin.setup:
  when: ansible_os_family is not defined
- name: Set non-Tailscale IP to default IPv4
  when:
    - ansible_os_family != "Windows" 
    - ansible_default_ipv4.address is defined
    - ansible_default_ipv4.address is match('^10\\.')
  set_fact:
    non_tailscale_ip: "{{ ansible_default_ipv4.address }}"
- name: Update ansible_host to non-Tailscale IP
  when:
    - non_tailscale_ip is defined
    - ansible_os_family != "Windows" 
  set_fact:
    ansible_host: "{{ non_tailscale_ip }}"
- name: Include install tasks
  ansible.builtin.include_tasks: install.yaml
  when: tailscale_state | default('present') == 'present'

- name: Include uninstall tasks
  ansible.builtin.include_tasks: uninstall.yaml
  when: tailscale_state | default('present') == 'absent'
