---
# roles/tailscale_manage/tasks/main.yaml

- name: Gather facts if needed
  ansible.builtin.setup:
  when: ansible_os_family is not defined

- name: Include install tasks
  ansible.builtin.include_tasks: install.yaml
  when: tailscale_state | default('present') == 'present'

- name: Include uninstall tasks
  ansible.builtin.include_tasks: uninstall.yaml
  when: tailscale_state | default('present') == 'absent'
