# roles/tailscale_manage/tasks/install.yaml
- name: Uninstall Tailscale on Windows
  when: ansible_os_family == "Windows"
  ansible.builtin.include_tasks: windows-uninstall.yaml

- name: Uninstall Tailscale on Linux
  when: ansible_os_family != "Windows"
  ansible.builtin.include_tasks: linux-uninstall.yaml