# roles/tailscale_manage/tasks/uninstall.yaml
- name: Check if Tailscale service exists on Windows
  when: ansible_os_family == "Windows"
  ansible.windows.win_service:
    name: Tailscale
  register: tailscale_service
  failed_when: false

- name: Set fact for Tailscale installation status on Windows
  when: ansible_os_family == "Windows"
  ansible.builtin.set_fact:
    tailscale_windows_installed:
      rc: "{{ 0 if tailscale_service.exists else 1 }}"

- name: Check if Tailscale is installed on Linux
  when: ansible_os_family != "Windows"
  ansible.builtin.command: which tailscale
  register: tailscale_linux_installed
  changed_when: false
  failed_when: false

- name: Uninstall Tailscale on Windows
  when: 
    - ansible_os_family == "Windows"
    - tailscale_windows_installed.rc == 0
  ansible.builtin.include_tasks: windows-uninstall.yaml

- name: Uninstall Tailscale on Linux
  when: 
    - ansible_os_family != "Windows"
    - tailscale_linux_installed.rc == 0
  ansible.builtin.include_tasks: linux-uninstall.yaml

- name: Print message if Tailscale is not installed
  debug:
    msg: "Tailscale doesn't appear to be installed"
  when: 
    - (ansible_os_family == "Windows" and tailscale_windows_installed.rc != 0) or
      (ansible_os_family != "Windows" and tailscale_linux_installed.rc != 0)