# roles/tailscale_manage/tasks/uninstall.yaml
- name: Check if Tailscale is installed on Windows
  when: ansible_os_family == "Windows"
  ansible.windows.win_shell: |
    $tailscaleInstalled = Get-WmiObject -Class Win32_Product | Where-Object { $_.Name -like "*Tailscale*" }
    if ($tailscaleInstalled) {
        Write-Output "Tailscale is installed"
        exit 0
    } else {
        Write-Output "Tailscale is not installed"
        exit 1
    }
  register: tailscale_windows_installed
  changed_when: false
  failed_when: false

- name: Uninstall Tailscale on Windows
  when: 
    - ansible_os_family == "Windows"
    - tailscale_windows_installed.rc == 0
  ansible.builtin.include_tasks: windows-uninstall.yaml


- name: Check if Tailscale is installed on Linux
  when: ansible_os_family != "Windows"
  ansible.builtin.command: which tailscale
  register: tailscale_linux_installed
  changed_when: false
  failed_when: false

- name: Uninstall Tailscale on Linux
  when: 
    - ansible_os_family != "Windows"
    - tailscale_linux_installed.rc == 0
  ansible.builtin.include_tasks: linux-uninstall.yaml

- name: Print message if Tailscale is not installed
  debug:
    msg: "Tailscale doesn't appear to be installed"
  when: 
    - (ansible_os_family == "Windows" and not tailscale_windows_installed.exists) or
      (ansible_os_family != "Windows" and tailscale_linux_installed.rc != 0)