# roles/tailscale_manage/tasks/uninstall.yaml
- name: Get device ID on Windows
  win_shell: |
    $status = & '{{ ansible_env.ProgramFiles }}\\Tailscale\\tailscale.exe' status --json | ConvertFrom-Json
    $status.Self.ID
  register: tailscale_status_windows
  ignore_errors: yes
  when: ansible_os_family == 'Windows'

- name: Get device ID on Linux
  ansible.builtin.shell: |
    tailscale status --json | python3 -c "import sys, json; print(json.load(sys.stdin)['Self']['ID'])"
  register: tailscale_status_linux
  ignore_errors: yes
  when: ansible_os_family != 'Windows'

- name: Set device ID fact
  set_fact:
    tailscale_device_id: "{{ tailscale_status_windows.stdout | default(tailscale_status_linux.stdout, true) }}"
  when: tailscale_status_windows is success or tailscale_status_linux is success

- name: Uninstall Tailscale on Windows
  block:
    - name: Set Windows-specific variables for uninstall
      set_fact:
        program_files_dir: "{{ ansible_env.ProgramFiles if (ansible_architecture in ['x86_64', 'amd64'] or ansible_env.PROCESSOR_ARCHITECTURE == 'AMD64') else ansible_env.ProgramFiles(x86) | default(ansible_env.ProgramFiles) }}"

    - name: Uninstall Tailscale
      win_package:
        path: '{{ program_files_dir }}\\Tailscale\\tailscale-setup.msi'
        state: absent

    - name: Remove Tailscale directory
      win_file:
        path: '{{ program_files_dir }}\\Tailscale'
        state: absent

    - name: Remove Tailscale data directory
      win_file:
        path: '{{ ansible_env.ProgramData }}\\Tailscale'
        state: absent
  when: ansible_os_family == "Windows"

- name: Uninstall Tailscale on Linux
  block:
    - name: Uninstall Tailscale package
      ansible.builtin.package:
        name: tailscale
        state: absent
      become: yes

    - name: Remove Tailscale data directory
      ansible.builtin.file:
        path: /var/lib/tailscale
        state: absent
      become: yes

    - name: Remove Tailscale configuration
      ansible.builtin.file:
        path: /etc/tailscale
        state: absent
      become: yes
  when: ansible_os_family != "Windows"
- name: Remove device from tailnet
  uri:
    url: "https://api.tailscale.com/api/v2/device/{{ tailscale_device_id }}"
    method: DELETE
    headers:
      Authorization: "Bearer {{ tailscale_api_key }}"
  delegate_to: localhost
  register: result

- name: Debug the result
  debug:
    var: result
