# roles/tailscale_manage/tasks/windows-uninstall.yaml
- name: Get device ID on Windows
  when: ansible_os_family == "Windows"
  win_shell: |
    $status = & '{{ ansible_env.ProgramFiles }}\\Tailscale\\tailscale.exe' status --json | ConvertFrom-Json
    $status.Self.ID
  register: tailscale_status_windows
  ignore_errors: yes

- name: Set device ID fact
  when: 
    - ansible_os_family == "Windows"
    - tailscale_status_windows is success
  set_fact:
    tailscale_device_id: "{{ tailscale_status_windows.stdout }}"

- name: Uninstall Tailscale on Windows
  when: ansible_os_family == "Windows"
  block:
    - name: Determine system architecture for Windows
      set_fact:
        is_64bit: "{{ ansible_architecture in ['x86_64', 'amd64'] or ansible_env.PROCESSOR_ARCHITECTURE == 'AMD64' }}"

    - name: Set Windows-specific variables for uninstall
      set_fact:
        program_files_dir: "{{ ansible_env.ProgramFiles if is_64bit else ansible_env.ProgramFiles(x86) | default(ansible_env.ProgramFiles) }}"
        tailscale_msi_url: "https://pkgs.tailscale.com/stable/tailscale-setup-latest-{{ 'amd64' if is_64bit else 'x86' }}.msi"
        tailscale_msi_path: '{{ program_files_dir }}\\Tailscale\\tailscale-setup.msi'

    - name: Check if Tailscale MSI exists
      win_stat:
        path: "{{ tailscale_msi_path }}"
      register: tailscale_msi_stat

    - name: Download Tailscale MSI if not present
      win_get_url:
        url: "{{ tailscale_msi_url }}"
        dest: "{{ tailscale_msi_path }}"
      when: not tailscale_msi_stat.stat.exists

    - name: Uninstall Tailscale
      win_package:
        path: "{{ tailscale_msi_path }}"
        state: absent

    - name: Remove Tailscale directory
      win_file:
        path: '{{ program_files_dir }}\\Tailscale'
        state: absent

    - name: Remove Tailscale data directory
      win_file:
        path: '{{ ansible_env.ProgramData }}\\Tailscale'
        state: absent

- name: Remove device from tailnet
  uri:
    url: "https://api.tailscale.com/api/v2/device/{{ tailscale_device_id }}"
    method: DELETE
    headers:
      Authorization: "Bearer {{ tailscale_api_key }}"
  delegate_to: localhost
  register: result

- name: Debug the result
  debug:
    var: result